name: Run Data Center Monitor

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
  run: pip install feedparser pandas openpyxl matplotlib requests


      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py

      - name: Check output file exists
        run: |
          echo "--- FILES IN FOLDER ---"
          ls -la
          echo "--- FILE INFO ---"
          file data_center_monitoring.xlsx || echo "Excel not found"

      - name: Commit output file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase || true
          git add data_center_monitoring.xlsx || true
          git status
          git diff --cached --quiet && echo "No changes to commit" || \
            (git commit -m "Update XLSX [auto]" && \
             git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || true)
