name: Run Data Center Monitor

on:
  schedule:
    - cron: "0 * * * *"  # co godzinę
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser pandas openpyxl matplotlib requests

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main_larget_datacenter.py

      - name: Commit output file exists
        run: |
          echo "--- FILES IN FOLDER ---"
          ls -la
          echo "--- FILE INFO ---"
          file data_center_monitoring.csv || echo "Excel not found"

      - name: Commit output file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data_center_monitoring.csv projekty_wg_*.png || true
          git commit -m "Auto update monitoring data [skip ci]" || echo "No changes"
          git push
